### PR TITLE
feature: Keep a local copy of the provider list - solves #64

### PR DESCRIPTION
**Pull request by testower**
First draft. Trying to wrap my head around how to test this properly.

### CODE REVIEW

**Comment by raae** [comment]
Looks good! 

Travis is failing because of prettier conflicts, try `npm run format` and push again.

**Comment by testower** [comment]
> Travis is failing because of prettier conflicts, try `npm run format` and push again.

Strange! I ran that locally and there's no changes.

**Comment by raae** [comment]
> > Travis is failing because of prettier conflicts, try `npm run format` and push again.
> 
> Strange! I ran that locally and there's no changes.

I'll look into it. Pretty new to this validation step and Travis ;)

**Comment by raae** [comment]
So far we have not implemented testing for the top level files, so we can leave that for now. But should be looked into.

**Pull request merged**
