### PR TITLE
Initialize scripts on onInitialClientRender

### LINKED ISSUE #74: Init scripts also on initialClientRender
@adamwiggall made me aware we need to `processInstagram` and `loadTwitter` also on `onInitalClientLoad`.

I would combine `processInstagram` and `loadTwitter` in a `initScripts` function and call that both from both `onInitalClientLoad` and `onRouteUpdate`. 

The code for this can be found in `gatsby-browser.js`.

### PR DESCRIPTION
**Pull request by victornguyen**
If needed, this closes #74 

🙌

### CODE REVIEW

**Comment by raae** [comment]
Hey, thanks! 

I am a little behind with PRs, but will try to merge soon :D

**Comment by raae** [comment]
Could someone on the @gatsbyjs team shed some light on this? Maybe @jlengstorf or @pieh?

**Comment by jlengstorf** [comment]
@raae we'll probably get a more thorough response from @pieh, but `onRouteUpdate` isn't triggered on initial page load, so I believe this PR is a good one.

**Comment by raae** [comment]
Thanks @jlengstorf! 

I checked the docs again and it does say "user changes routes".

**Pull request merged**
