### PR TITLE
Handling for custom prefixes

### LINKED ISSUE #47: Add support for an array of prefixes
Lets users define their own prefixes like `video:`.

This would give users more control over their content, and also make it easier to migrate from other plugins were other prefixes have been used.

There are plugins for youtube, twitter etc. specifically. And the users of those will probably have lots of content already using a specific prefix.

In config `usePrefix: ["video:", "oembed:"]`.

### PR DESCRIPTION
**Pull request by rayriffy**
closes #47 

~~I haven't change test unit yet, so I will definitely fail. (ノ_<。)~~ Now I updated test units please also verify them.

### CODE REVIEW

**Comment by raae** [comment]
I have added you as a collaborator so in the future, you can create branches and we can collaborate.

I think Travis is failing because of error with prettier formatting. Try running `npm run format`.

**Comment by rayriffy** [comment]
I think it's ready to merge now! ヽ(・∀・)ﾉ

**Comment by raae** [comment]
Thanks, will look at this early next week if I do not get to it over the weekend.

**Comment by raae** [comment]
We still need to support `usePrefix: true`.
Maybe change `true` for `["oembed"]` in amendOptions?
I can also merge this if you'd like and then I could add this later.

**Comment by rayriffy** [comment]
I can work on this just please give me some time. :)

**Comment by raae** [comment]
> I can work on this just please give me some time. :)

No problem :D

**Comment by rayriffy** [comment]
Last failed commit is fail because the test unit is preferring a default option which is `usePrefix = false` and there's no any node that match those.

I think it should be fine now, just add more test unit after this PR merged.

**Comment by raae** [comment]
No worries, we all have other things to do. Will hopefully get it merged this weekend together with some more maintenance work and then maybe go for a 1.0.0 release :D

**Comment by raae** [comment]
Replaced by PR #78

**Pull request closed without merging**
