### PR TITLE
loadTwitter and processInstagram onInitialClientRender

### PR DESCRIPTION
**Pull request by jbhannah**

### CODE REVIEW

**Comment by raae** [comment]
Hi, thanks for using and giving feedback!

Did this now work after all?

**Comment by jbhannah** [comment]
It didn't — I'm still not sure why it's happening, but it's now happening intermittently. It appears that it might be related to whether or not the Twitter embed script is cached. Still poking around.

**Comment by raae** [comment]
Do you have the code up on github so I could test locally?

**Comment by jbhannah** [comment]
Yes - https://github.com/jbhannah/jbhannah.net

**Comment by raae** [comment]
Thanks! I think maybe you were onto something with the PR. There might not be a `exports.onRouteUpdate` when landing on the home page directly.

**Comment by raae** [comment]
No, that is not it.

**Comment by raae** [comment]
I think the challenge is the Markdown component, and that it rerenders precisely as the scripts are loaded. The scripts from Twitter looks through the HTML to find twitter embeds to enhance, and there are none. Or it enhanced them, but then the component renders and it's lost. Not 100% sure 

If you look at [the example repo](https://github.com/raae/gatsby-remark-oembed-example-site) you see it uses the HTML generated from the `gatsby-transformer-remark`.

**Pull request closed without merging**
